name: Laravel_CICD
on: ["push"]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v6

            - name: Setup PHP and disable opcache
              uses: shivammathur/setup-php@v2
              with:
                php-version: '8.2'
                extensions: :json,libxml,xml,,xmlwriter,mbstring,tokenizer,openssl

            - name: Install dependencies
              run: composer install

            - name: Copy env files
              run: cp .env.example .env

            - name: Generate application key
              run: php artisan key:generate

            - name: List the application 
              run: ls
              
            - name:  Run test cases
              run: php artisan test
            
